### ISSUE TITLE
Add Build/Test GitHub Action

### ISSUE THREAD

**Issue by gaaliciA1990** [CodeHavenX/MonoRepo#11]
Implement a github action that will build and run the tests for the alpaca scheduler. 
Add it to the branch protections so that PRs are automatically required to have them pass before a merge is available.
Add the badges to the project

**Comment by CRamsan** [comment]
We have the github actions running. They run as part of the `./gradlew releaseAll` task. This task will run the `./gradlew alpaca-scheduler:back-end:release` tasks, which will then compile and run all the tests.

Branch protection is also enabled, although we have the option to override it. I suggest we allow the override for cases in which we need to make changes to code that is not part of the 🦙 scheduler project. 

Badge completions would be great to have 👍
